---
# https://help.ubnt.com/hc/en-us/articles/220066768-UniFi-How-to-Install-Update-via-APT-on-Debian-or-Ubuntu
# https://www.technologist.site/2016/06/02/how-to-install-ubiquiti-unifi-controller-5-on-the-raspberry-pi/3/
# https://lazyadmin.nl/it/installing-unifi-controller-on-a-raspberry-pi-in-5-min/
- name: install openjdk-8-jre-headless
  apt:
    name: openjdk-8-jre-headless
    state: present
  become: yes
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == "16.04"
- name: add unifi apt key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 06E85760C0A52C50
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == "16.04"
- name: add unifi repo
  apt_repository:
    repo: deb http://www.ubnt.com/downloads/unifi/debian stable ubiquiti
    state: present
    filename: 100-ubnt-unifi
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == "16.04"
- name: update repositories cache
  apt:
    update_cache: yes
  become: yes
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == "16.04"
- name: install unifi
  apt:
    name: unifi
    state: present
  become: yes
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == "16.04"
- name: stop mongodb service
  systemd:
    name: mongodb
    state: stopped
  become: yes
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == "16.04"
# https://stackoverflow.com/a/28070759
- name: disable mongodb service
  systemd:
    name: mongodb
    enabled: no
  become: yes
  notify:
    - restart server
    - wait for server to restart
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == "16.04"
