---
- name: create directory for docker config override
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    mode: 0755

- name: create file for docker config override
  template:
    src: startup_options.conf.j2
    dest: /etc/systemd/system/docker.service.d/startup_options.conf
    owner: root
    group: root
    mode: 0644

- name: add docker's apt signing key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: yes

- name: add docker's apt repo
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu artful stable
    state: present
  become: yes

- name: update repositories cache
  apt:
    update_cache: yes
  become: yes

- name: install docker-ce
  apt:
    name: docker-ce
    state: present
  become: yes

- name: add user "{{ ansible_user_id }}" to docker group
  user:
    append: yes
    name: "{{ ansible_user_id }}"
    groups: docker
  become: yes
